spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.58:3306/edb_a10000
        username: root
        password: Server-wms654321
mybatis:
    config-location: