spring:
    datasource:
        master:
            url: jdbc:mysql://192.168.1.58:3306/edb_a20000?useSSL=false
            username: root
            password: Server-wms654321
        slave:
            url: jdbc:mysql://192.168.1.58:3306/edb_b20000?useSSL=false
            username: root
            password: Server-wms654321

    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456

#mybatis:
#    config-location: classpath:mybatis-config.xml
#    type-aliases-package: com.yuanwj.mybatisdemo.model
#    configuration:
#        map-underscore-to-camel-case: true
#    mapper-locations: classpath:mapper/**/*.xml

server:
    port: 8081