#spring:
#    application:
#        name: mybatis-demo
#    cloud:
#        config:
#            uri: http://localhost:8087

spring:
    application:
        name: mybatis-demo
    datasource:
        master:
            url: jdbc:mysql://${mybatis-demo.ip}:3306/edb_a20000?useSSL=false
#            url: jdbc:mysql://192.168.1.58:3306/edb_a20000?useSSL=false
            username: root
            password: 123456
        slave:
            url: jdbc:mysql://${mybatis-demo.ip}:3306/edb_b20000?useSSL=false
            username: root
            password: 123456

    redis:
#        cluster:
#            nodes: localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384
        password: 123456
#        host: 127.0.0.1
#        port: 6379
#        password: 123456
        sentinel:
            master: master
            nodes: ${mybatis-demo.ip}:26379,${mybatis-demo.ip}:26380,${mybatis-demo.ip}:26381

server:
    port: 8083





#     public ApiInfo(String title, String description, String version,
# String termsOfServiceUrl, Contact contact, String license, String licenseUrl) {
mybatis-demo:
    swagger:
        title: mybatis-demo api document
        description: springboot与mybatis学习
        version: 0.1
        serviceUrl: https://yuanwenjian.github.io/
        name: yuanwj
        email: yuanwj0929@gmail.com

    ip: 10.10.120.64

##mybatis:
##    config-location: classpath:mybatis-config.xml
##    type-aliases-package: com.yuanwj.mybatisdemo.model
##    configuration:
##        map-underscore-to-camel-case: true
##    mapper-locations: classpath:mapper/**/*.xml
#
#server:
#    port: 8083
#eureka:
#    instance:
#        hostname: localhost
#        metadataMap:
#            instanceId: ${spring.application.name}:${random.value}
#    client:
#        service-url:
##            defaultZone: http://192.168.50.150:8081/eureka,http://192.168.50.150:8082/eureka
#            defaultZone: http://110.10.100.11:8081/eureka,http://10.10.100.11:8082/eureka